server:
  port: 8181
  servlet:
    context-path: /

spring:
  application:
    name: isg-digkeyapplication
  aop:
    proxy-target-class: true
    auto: true
  resources:
    static-locations: classpath:/static/,classpath:/public/   #ResourceProperties.java
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.101.198.174:1433;DatabaseName=sfa_henkel
    username: sfa
    password: sfa2020@wifi
  redis: # RedisProperties RedisAutoConfiguration
    database: 3
    host: r-uf6x1t7civ7hg9hopcpd.redis.rds.aliyuncs.com
    port: 6379
    timeout: 30000
    password: isg@1qaz0okm543520
    pool:
      max-wait: -1

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
  servlet:
    multipart:
      enabled: true
      max-request-size: 1024MB
      max-file-size: 1024MB
      file-size-threshold: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: basic
      isg-microservice-user:
        loggerLevel: full


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 5000
  ConnectTimeout: 3000
  ReadTimeout: 3000

pgyer:
  apikey: 815f5cac193de6fad72fde2a6db033a1

