server:
  port: 20001
  servlet:
    context-path: /yqbigdataweb

spring:
  application:
    name: springboot-base
  aop:
    proxy-target-class: true
    auto: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/,classpath:templates/   #ResourceProperties.java
  datasource:
    druid:
      url: jdbc:mysql://106.14.245.171:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Fine198908
      driver-class-name: com.mysql.cj.jdbc.Driver
      minIdle: 2
      maxActive: 2


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


pgyer:
  apikey: 815f5cac193de6fad72fde2a6db033a1

#elasticsearch:
#  clientIps: 106.14.245.171
#  httpPort: 9200
  #username: test
  #password: 123456

esParam:
  indexName: school
  indexType: student
  bulkSize: 500
  docNum: 200000000

nacos:
  config:
    namespace: bc503dc5-5815-4a4e-89dc-cb5da3b2f903



